#!/bin/bash

ps -eo rss,%mem,pid,euser,args:100 --sort %mem \
    | {
        head -1 ; \
        grep -v grep | grep -i $@ \
        | awk '{ tot += $1; per += $2; printf "%.2fMB ", $1/1024; $1=""; printf $2 "%%"; $2=""; print}\
        END { printf ("%s %s\n", "avg-rss", "avg-%mem" ); printf ("%.2fMB %.2f%s\n", tot/NR/1024, per/NR, "%%" ) }'
    } \
    | column -t
